const SUCCESS = 1;
const FALIURE = 2;
const ERROR_VALIDATION_FAILED = 3;
const ERROR_SOMETHING_BAD_HAPPEND = 4;
const ERROR_INVALID_EMAIL_PASSWORD = 5;
const ERROR_EMAIL_ALREADY_EXISTS = 6;
const ERROR_NO_PERMISSION = 7;
const ERROR_INVALID_EMAIL_TOKEN = 8;
const ERROR_EXPIRED_TOKEN = 9;
const ERROR_ACCOUNT_VERIFICATION = 10;

module.exports = {
  SUCCESS,
  FALIURE,
  ERROR_VALIDATION_FAILED,
  ERROR_SOMETHING_BAD_HAPPEND,
  ERROR_INVALID_EMAIL_PASSWORD,
  ERROR_EMAIL_ALREADY_EXISTS,
  ERROR_NO_PERMISSION,
  ERROR_INVALID_EMAIL_TOKEN,
  ERROR_EXPIRED_TOKEN,
  ERROR_ACCOUNT_VERIFICATION,
};
